sudo: false
language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++6-4.7
            - g++-4.7
            - gdb
            - libegl1-mesa-dev
            - libasound2-dev
            - libxss-dev
            - liblua5.1-0-dev
            - liblua5.1-0-dbg
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
before_install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
env:
    - NOTHING=1
    - FULLDEBUG=1
    - TILES=1
    - TILES=1 FULLDEBUG=1
    - WEBTILES=1
    - WEBTILES=1 FULLDEBUG=1
    - USE_DGAMELAUNCH=1 EXTERNAL_DEFINES=-UTOURNEY
    - USE_DGAMELAUNCH=1 WEBTILES=1 EXTERNAL_DEFINES=-UTOURNEY
    - TILES=1 BUILD_ALL=1
    - WEBTILES=1 BUILD_ALL=1
    - MONSTER=1
git:
    submodules: false
install: perl .travis/deps.pl
script: perl .travis/build.pl
notifications:
    email:
        on_success: change
        on_failure: always
#        recipients:
#          - crawl-ref-commits@lists.sourceforge.net
    irc:
        channels: "chat.freenode.net##crawl-dev"
        on_success: change
        on_failure: always
        use_notice: true
        template:
            - "%{message} (%{branch} - %{commit} #%{build_number} : %{author}): %{build_url}"
